# =========================================
# COPY MODE (VIM STYLE) - สำหรับ Ubuntu Server (Headless)
# =========================================

setw -g mode-keys vi

unbind [
bind Escape copy-mode

bind -T copy-mode-vi v send -X begin-selection
# ใช้ OSC 52 แทน xclip (เพราะ Ubuntu Server ไม่มี Display)
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi MouseDragEnd1Pane \
  send -X copy-selection-and-cancel

# paste clipboard (ใช้ OSC 52 เช่นกัน)
bind p paste-buffer
